files:
  include: '**/*.s+(a|c)ss'

options:
  formatter: stylish
  merge-default-rules: false

rules:

  bem-depth:
    - 0
    - max-depth: 1

  border-zero:
    - 1
    - convention: zero

  brace-style:
    - 1
    - allow-single-line: true

  class-name-format:
    - 1
    - convention: '^[a-z]{1}[a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*$'

  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: true

  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true

  extends-before-declarations: 1

  extends-before-mixins: 1

  final-newline:
    - 1
    - include: true

  force-attribute-nesting: 1

  force-element-nesting: 1

  force-pseudo-nesting: 1

  function-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '^[a-zA-Z]{1}[a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*$'

  hex-length:
    - 1
    - style: short

  hex-notation:
    - 1
    - style: lowercase

  id-name-format:
    - 1
    - convention: '^[a-z]{1}[a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*$'

  indentation:
    - 1
    - size: 2

  leading-zero:
    - 1
    - include: false

  mixin-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '^[a-zA-Z]{1}[a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*$'

  mixins-before-declarations:
    - 1
    - exclude: ['breakpoint', 'mq', 'tx-media', 'tx-mq']

  nesting-depth:
    - 1
    - max-depth: 4

  no-color-keywords: 1

  no-color-literals: 1

  no-css-comments: 0

  no-debug: 1

  no-duplicate-properties: 0

  no-empty-rulesets: 1

  no-extends: 0

  no-ids: 1

  no-important: 1

  no-invalid-hex: 1

  no-mergeable-selectors: 1

  no-misspelled-properties:
    - 1
    - extra-properties:
        - '-webkit-overflow-scrolling'
        - '-ms-interpolation-mode'
        - overscroll-behavior
        - font-display
        - '-epub-hyphens'

  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false

  no-trailing-zero: 1

  no-transition-all: 0

  no-url-protocols: 1

  no-vendor-prefixes:
    - 1
    - ignore-non-standard: false
    - additional-identifiers: []
      excluded-identifiers:
        - hyphens

  placeholder-in-extend: 1

  placeholder-name-format:
    - 1
    - convention: '^[a-z]{1}[a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*$'

  property-sort-order:
    - 1
    - ignore-custom-properties: false
      order:
        - position
        - z-index
        - top
        - right
        - bottom
        - left
        - content
        - counter-increment
        - counter-reset
        - quotes
        - '-webkit-appearance'
        - '-moz-appearance'
        - appearance
        - display
        - float
        - clear
        - order
        - align-items
        - align-content
        - justify-content
        - align-self
        - flex
        - flex-flow
        - flex-direction
        - flex-wrap
        - flex-grow
        - flex-shrink
        - flex-basis
        - grid
        - grid-area
        - grid-template
        - grid-template-areas
        - grid-template-rows
        - grid-template-columns
        - grid-column
        - grid-column-start
        - grid-column-end
        - grid-row
        - grid-row-start
        - grid-row-end
        - grid-auto-rows
        - grid-auto-columns
        - grid-auto-flow
        - grid-gap
        - grid-row-gap
        - grid-column-gap
        - overflow
        - overflow-x
        - overflow-y
        - '-webkit-overflow-scrolling'
        - '-ms-overflow-style'
        - overflow-scrolling
        - overscroll-behavior
        - scroll-snap-points-y
        - scroll-snap-points-x
        - scroll-snap-type
        - scroll-snap-destination
        - clip
        - box-sizing
        - '-webkit-box-decoration-break'
        - box-decoration-break
        - width
        - height
        - min-width
        - min-height
        - max-width
        - max-height
        - size
        - resize
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - border
        - border-spacing
        - border-collapse
        - border-width
        - border-style
        - border-color
        - border-top
        - border-top-width
        - border-top-style
        - border-top-color
        - border-right
        - border-right-width
        - border-right-style
        - border-right-color
        - border-bottom
        - border-bottom-width
        - border-bottom-style
        - border-bottom-color
        - border-left
        - border-left-width
        - border-left-style
        - border-left-color
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-right-radius
        - border-bottom-left-radius
        - border-image
        - border-image-source
        - border-image-slice
        - border-image-width
        - border-image-outset
        - border-image-repeat
        - border-top-image
        - border-right-image
        - border-bottom-image
        - border-left-image
        - border-corner-image
        - border-top-left-image
        - border-top-right-image
        - border-bottom-right-image
        - border-bottom-left-image
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - color
        - background
        - background-color
        - background-image
        - background-attachment
        - background-position
        - background-position-x
        - background-position-y
        - background-clip
        - background-origin
        - background-size
        - background-repeat
        - outline
        - outline-width
        - outline-style
        - outline-color
        - outline-offset
        - '-webkit-tap-highlight-color'
        - tap-highlight-color
        - box-decoration-break
        - box-shadow
        - font
        - font-weight
        - font-style
        - font-variant
        - font-size-adjust
        - font-stretch
        - font-size
        - font-family
        - font-feature-settings
        - font-display
        - src
        - text-align
        - text-align-last
        - text-decoration
        - text-decoration-color
        - text-decoration-style
        - text-decoration-skip
        - text-emphasis
        - text-emphasis-position
        - text-emphasis-style
        - text-emphasis-color
        - text-indent
        - text-justify
        - text-outline
        - text-transform
        - text-wrap
        - text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - text-size-adjust
        - text-shadow
        - text-rendering
        - letter-spacing
        - line-height
        - vertical-align
        - white-space
        - word-spacing
        - word-wrap
        - word-break
        - tab-size
        - '-epub-hyphens'
        - '-webkit-hyphens'
        - '-moz-hyphens'
        - hyphens
        - unicode-bidi
        - direction
        - columns
        - column-span
        - column-width
        - column-count
        - column-fill
        - column-gap
        - column-rule
        - column-rule-width
        - column-rule-style
        - column-rule-color
        - page-break-before
        - break-before
        - page-break-inside
        - break-inside
        - page-break-after
        - break-after
        - orphans
        - widows
        - list-style
        - list-style-position
        - list-style-type
        - list-style-image
        - table-layout
        - caption-side
        - empty-cells
        - visibility
        - opacity
        - interpolation-mode
        - filter
        - cursor
        - pointer-events
        - touch-action
        - user-select
        - nav-index
        - nav-up
        - nav-right
        - nav-down
        - nav-left
        - zoom
        - max-zoom
        - min-zoom
        - user-zoom
        - orientation
        - transform
        - transform-origin
        - transition
        - transition-delay
        - transition-timing-function
        - transition-duration
        - transition-property
        - animation
        - animation-name
        - animation-duration
        - animation-play-state
        - animation-timing-function
        - animation-delay
        - animation-iteration-count
        - animation-direction
        - stroke
        - stroke-width
        - stroke-dasharray
        - stroke-dashoffset
        - stroke-linecap
        - fill
        - vector-effect
        - mask
        - clip-path
        - '-premailer-width'
        - '-premailer-cellpadding'
        - '-premailer-cellspacing'

  property-units:
    - 1
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}

  quotes:
    - 1
    - style: single

  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 3
        - 4

  single-line-per-selector: 1

  space-after-bang:
    - 1
    - include: false

  space-after-colon:
    - 1
    - include: true

  space-after-comma:
    - 1
    - include: true

  space-before-bang:
    - 1
    - include: true

  space-before-brace:
    - 1
    - include: true

  space-before-colon: 1

  space-between-parens:
    - 1
    - include: false

  trailing-semicolon: 1

  url-quotes: 1

  variable-for-property:
    - 0
    - properties: []

  variable-name-format:
    - 1
    - allow-leading-underscore: false
      convention: '^[a-zA-Z]{1}[a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*$'

  zero-unit: 1
